# Generated by Django 6.0.1 on 2026-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdrop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fruits'), ('vegetable', 'Vegetables'), ('grain', 'Grains')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
